# Generated by Django 5.0.6 on 2026-03-07 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_stock_alter_product_id_alter_tag_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la tienda')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción / Referencia')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Tienda Física',
                'verbose_name_plural': 'Tiendas Físicas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WholesaleClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Empresa / Negocio')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('notes', models.TextField(blank=True, verbose_name='Notas internas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Cliente Mayorista',
                'verbose_name_plural': 'Clientes Mayoristas',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='WholesalePurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='store.wholesaleclient', verbose_name='Cliente')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wholesale_purchases', to='store.product', verbose_name='Producto')),
                ('product_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wholesale_purchases', to='store.productsize', verbose_name='Talla')),
            ],
            options={
                'verbose_name': 'Compra Mayorista',
                'verbose_name_plural': 'Compras Mayoristas',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StoreInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Cantidad asignada')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_inventory', to='store.product', verbose_name='Producto')),
                ('product_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_inventory', to='store.productsize', verbose_name='Talla')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='store.physicalstore', verbose_name='Tienda')),
            ],
            options={
                'verbose_name': 'Inventario en Tienda',
                'verbose_name_plural': 'Inventario en Tiendas',
                'unique_together': {('store', 'product_size')},
            },
        ),
    ]
